export const jobOpenings = [
    {
      id: 1,
      brandLogo: "https://logo.clearbit.com/google.com",
      companyName: "Google",
      datePosted: "5 days ago",
      post: "Frontend Developer",
      tag1: "Full Time",
      tag2: "Junior Level",
      pay: "$35/hr",
      location: "Mumbai, India",
    },
    {
      id: 2,
      brandLogo: "https://logo.clearbit.com/amazon.com",
      companyName: "Amazon",
      datePosted: "2 weeks ago",
      post: "Backend Developer",
      tag1: "Full Time",
      tag2: "Senior Level",
      pay: "$45/hr",
      location: "Mumbai, India",
    },
    {
      id: 3,
      brandLogo: "https://logo.clearbit.com/microsoft.com",
      companyName: "Microsoft",
      datePosted: "10 days ago",
      post: "Software Engineer",
      tag1: "Full Time",
      tag2: "Mid Level",
      pay: "$40/hr",
      location: "Mumbai, India",
    },
    {
      id: 4,
      brandLogo: "https://logo.clearbit.com/netflix.com",
      companyName: "Netflix",
      datePosted: "3 weeks ago",
      post: "UI/UX Designer",
      tag1: "Part Time",
      tag2: "Junior Level",
      pay: "$30/hr",
      location: "Mumbai, India",
    },
    {
      id: 5,
      brandLogo: "https://logo.clearbit.com/spotify.com",
      companyName: "Spotify",
      datePosted: "1 week ago",
      post: "Product Designer",
      tag1: "Full Time",
      tag2: "Senior Level",
      pay: "$42/hr",
      location: "Mumbai, India",
    },
    {
      id: 6,
      brandLogo: "https://logo.clearbit.com/airbnb.com",
      companyName: "Airbnb",
      datePosted: "6 days ago",
      post: "Full Stack Developer",
      tag1: "Full Time",
      tag2: "Mid Level",
      pay: "$38/hr",
      location: "Mumbai, India",
    },
    {
      id: 7,
      brandLogo: "https://logo.clearbit.com/uber.com",
      companyName: "Uber",
      datePosted: "10 weeks ago",
      post: "Mobile App Developer",
      tag1: "Part Time",
      tag2: "Senior Level",
      pay: "$50/hr",
      location: "Mumbai, India",
    },
    {
      id: 8,
      brandLogo: "https://logo.clearbit.com/linkedin.com",
      companyName: "LinkedIn",
      datePosted: "4 days ago",
      post: "React Developer",
      tag1: "Full Time",
      tag2: "Junior Level",
      pay: "$28/hr",
      location: "Mumbai, India",
    },
    {
      id: 9,
      brandLogo: "https://logo.clearbit.com/adobe.com",
      companyName: "Adobe",
      datePosted: "8 weeks ago",
      post: "Creative Technologist",
      tag1: "Full Time",
      tag2: "Mid Level",
      pay: "$37/hr",
      location: "Mumbai, India",
    },
    {
      id: 10,
      brandLogo: "https://logo.clearbit.com/shopify.com",
      companyName: "Shopify",
      datePosted: "12 days ago",
      post: "Platform Engineer",
      tag1: "Full Time",
      tag2: "Senior Level",
      pay: "$48/hr",
      location: "Mumbai, India",
    },
  ];
  